version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my-network
    volumes:
      - wow:/app
    # depends_on:
      # - db
  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_PASSWORD: example
networks:
  my-network:

volumes:
  wow:
